const Projects = {
  games: [
    {
      id: "minesweeper",
      title: "minesweeper_title",
      description: "minesweeper_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20241201_ai_gallery_minesweeper_small.png",
      link: "/games/minesweeper",
    },
    {
      id: "sliding",
      title: "sliding_title",
      description: "sliding_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20241031_ai_gallery_sliding_small.png",
      link: "/games/sliding",
    },
    {
      id: "sokoban",
      title: "sokoban_title",
      description: "sokoban_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20241116_ai_gallery_sokoban_small.png",
      link: "/games/sokoban",
    },
    {
      id: "lasermaze",
      title: "lasermaze_title",
      description: "lasermaze_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20251011_ai_gallery_lasermaze.webp",
      link: "/games/lasermaze",
    },
    {
      id: "unblockme",
      title: "unblockme_title",
      description: "unblockme_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20250924_ai_gallery_unblockme_small.webp",
      link: "/games/unblockme",
    },
    {
      id: "sudoku",
      title: "sudoku_title",
      description: "sudoku_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20241031_ai_gallery_sudoku_small.png",
      link: "/games/sudoku",
    },
    {
      id: "maze",
      title: "maze_title",
      description: "maze_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20241201_ai_gallery_maze_small.png",
      link: "/games/maze",
    },
    {
      id: "tangram",
      title: "tangram_title",
      description: "tangram_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20250516_ai_gallery_tangram.webp",
      link: "/games/tangram",
    },
    {
      id: "gomoku",
      title: "gomoku_title",
      description: "gomoku_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20241031_ai_gallery_gomoku_small.png",
      link: "/games/gomoku",
    },
    {
      id: "cube",
      title: "cube_title",
      description: "cube_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20241031_ai_gallery_cube_small.png",
      link: "/games/cube",
    },
    {
      id: "tetris",
      title: "tetris_title",
      description: "tetris_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20241031_ai_gallery_tetris_small.png",
      link: "/games/tetris",
    },
    {
      id: "snake",
      title: "snake_title",
      description: "snake_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20241031_ai_gallery_snake_small.png",
      link: "/games/snake",
    },
    {
      id: "2048",
      title: "2048_title",
      description: "2048_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20241031_ai_gallery_2048_small.png",
      link: "/games/2048",
    },
    {
      id: "chess",
      title: "chess_title",
      description: "chess_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20241031_ai_gallery_2048_chess.png",
      link: "/games/chess",
    },
  ],
  algorithms: [
    {
      id: "heap",
      title: "heap_title",
      description: "heap_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20240706_ai_gallery_heapv2.gif",
      link: "/algorithms/heap/",
    },
    {
      id: "hanoitower",
      title: "hanoitower_title",
      description: "hanoitower_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20240812_ai_gallery_hanoitower.webp",
      link: "/algorithms/hanoitower/",
    },
    {
      id: "hashtable",
      title: "hashtable_title",
      description: "hashtable_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20240726_ai_gallery_hashtable.webp",
      link: "/algorithms/hashtable/",
    },
    {
      id: "dpcoin",
      title: "dpcoin_title",
      description: "dpcoin_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20240730_ai_gallery_dpcoin.webp",
      link: "/algorithms/dpcoin/",
    },
    {
      id: "trie",
      title: "trie_title",
      description: "trie_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20240726_ai_gallery_trie.webp",
      link: "/algorithms/trie/",
    },
    {
      id: "binarysearchtree",
      title: "binarysearchtree_title",
      description: "binarysearchtree_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20240908_ai_gallery_binarysearchtree.webp",
      link: "/algorithms/binarysearchtree/",
    },
    {
      id: "avltree",
      title: "avltree_title",
      description: "avltree_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20240908_ai_gallery_binarysearchtree.webp",
      link: "/algorithms/avltree/",
    },
    {
      id: "bloomfilter",
      title: "bloomfilter_title",
      description: "bloomfilter_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20240805_ai_gallery_bloomfilter.webp",
      link: "/algorithms/bloomfilter/",
    },
    {
      id: "dijkstra",
      title: "dijkstra_title",
      description: "dijkstra_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20240709_ai_gallery_dijkstra_v3.gif",
      link: "/algorithms/dijkstra/",
    },
    {
      id: "stack",
      title: "stack_title",
      description: "stack_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20240726_ai_gallery_stack.webp",
      link: "/algorithms/stack/",
    },
    {
      id: "hashring",
      title: "hashring_title",
      description: "hashring_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20240801_ai_gallery_hashring.webp",
      link: "/algorithms/hashring/",
    },
    {
      id: "jumphash",
      title: "jumphash_title",
      description: "jumphash_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20240809_ai_gallery_jumphash.webp",
      link: "/algorithms/jumphash/",
    },
    {
      id: "kmp",
      title: "kmp_title",
      description: "kmp_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20260412_ai_gallery_kmp_cover.webp",
      link: "/algorithms/kmp/",
    },
    {
      id: "skiplist",
      title: "skiplist_title",
      description: "skiplist_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20240728_ai_gallery_skiplist.webp",
      link: "/algorithms/skiplist/",
    },
    {
      id: "astar",
      title: "astar_title",
      description: "astar_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20240706_ai_gallery_astar_path.gif",
      link: "/algorithms/astar/",
    },
    {
      id: "bfs_path",
      title: "bfs_path_title",
      description: "bfs_path_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20240706_ai_gallery_bfs_path.gif",
      link: "/algorithms/bfs_path/",
    },
    {
      id: "linkedlist",
      title: "linkedlist_title",
      description: "linkedlist_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20240726_ai_gallery_linkedlist.webp",
      link: "/algorithms/linkedlist/",
    },
    {
      id: "ratelimit",
      title: "ratelimit_title",
      description: "ratelimit_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20240716_ai_gallery_ratelimit.gif",
      link: "/algorithms/ratelimit/",
    },
    {
      id: "tokenbucket",
      title: "tokenbucket_title",
      description: "tokenbucket_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20240726_ai_gallery_tokenbucket.webp",
      link: "/algorithms/tokenbucket/",
    },
  ],
  tools: [
    {
      id: "gendocx",
      title: "gendocx_title",
      description: "gendocx_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_gendocx_en.svg",
      images: {
        en: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_gendocx_en.svg",
        zh: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_gendocx_zh.svg",
      },
      link: "/tools/gendocx/",
      tags: ["document", "excel"],
    },
    {
      id: "mergeword",
      title: "mergeword_title",
      description: "mergeword_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_mergeword_en.svg",
      images: {
        en: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_mergeword_en.svg",
        zh: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_mergeword_zh.svg",
      },
      link: "/tools/mergeword/",
      tags: ["document"],
    },
    {
      id: "splitword",
      title: "splitword_title",
      description: "splitword_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_splitword_en.svg",
      images: {
        en: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_splitword_en.svg",
        zh: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_splitword_zh.svg",
      },
      link: "/tools/splitword/",
      tags: ["document"],
    },
    {
      id: "mergepdf",
      title: "mergepdf_title",
      description: "mergepdf_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_mergepdf_en.svg",
      images: {
        en: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_mergepdf_en.svg",
        zh: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_mergepdf_zh.svg",
      },
      link: "/tools/mergepdf/",
      tags: ["pdf", "document"],
    },
    {
      id: "splitpdf",
      title: "splitpdf_title",
      description: "splitpdf_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_splitpdf_en.svg",
      images: {
        en: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_splitpdf_en.svg",
        zh: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_splitpdf_zh.svg",
      },
      link: "/tools/splitpdf/",
      tags: ["pdf", "document"],
    },
    {
      id: "imagepdf",
      title: "imagepdf_title",
      description: "imagepdf_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_imagepdf_en.svg",
      images: {
        en: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_imagepdf_en.svg",
        zh: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_imagepdf_zh.svg",
      },
      link: "/tools/imagepdf/",
      tags: ["pdf", "image"],
    },
    {
      id: "imagecompress",
      title: "imagecompress_title",
      description: "imagecompress_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_imagecompress_en.svg",
      images: {
        en: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_imagecompress_en.svg",
        zh: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_imagecompress_zh.svg",
      },
      link: "/tools/imagecompress/",
      tags: ["image", "media"],
    },
    {
      id: "pdforganize",
      title: "pdforganize_title",
      description: "pdforganize_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_pdforganize_en.svg",
      images: {
        en: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_pdforganize_en.svg",
        zh: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_pdforganize_zh.svg",
      },
      link: "/tools/pdforganize/",
      tags: ["pdf", "document"],
    },
    {
      id: "excelcompare",
      title: "excelcompare_title",
      description: "excelcompare_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_excelcompare_en.svg",
      images: {
        en: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_excelcompare_en.svg",
        zh: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_excelcompare_zh.svg",
      },
      link: "/tools/excelcompare/",
      tags: ["excel", "data"],
    },
    {
      id: "exceldedupe",
      title: "exceldedupe_title",
      description: "exceldedupe_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_exceldedupe_en.svg",
      images: {
        en: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_exceldedupe_en.svg",
        zh: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_exceldedupe_zh.svg",
      },
      link: "/tools/exceldedupe/",
      tags: ["excel", "data"],
    },
    {
      id: "excelclean",
      title: "excelclean_title",
      description: "excelclean_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_excelclean_en.svg",
      images: {
        en: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_excelclean_en.svg",
        zh: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_excelclean_zh.svg",
      },
      link: "/tools/excelclean/",
      tags: ["excel", "data"],
    },
    {
      id: "excelsplitmerge",
      title: "excelsplitmerge_title",
      description: "excelsplitmerge_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_excelsplitmerge_en.svg",
      images: {
        en: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_excelsplitmerge_en.svg",
        zh: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_excelsplitmerge_zh.svg",
      },
      link: "/tools/excelsplitmerge/",
      tags: ["excel", "data"],
    },
    {
      id: "exceljson",
      title: "exceljson_title",
      description: "exceljson_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_exceljson_en.svg",
      images: {
        en: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_exceljson_en.svg",
        zh: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_exceljson_zh.svg",
      },
      link: "/tools/exceljson/",
      tags: ["excel", "data", "developer"],
    },
    {
      id: "retire",
      title: "retire_title",
      description: "retire_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_retire_en.svg",
      images: {
        en: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_retire_en.svg",
        zh: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_retire_zh.svg",
      },
      link: "/tools/retire/",
      tags: ["finance"],
    },
    {
      id: "loanrate",
      title: "loanrate_title",
      description: "loanrate_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_loanrate_en.svg",
      images: {
        en: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_loanrate_en.svg",
        zh: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_loanrate_zh.svg",
      },
      link: "/tools/loanrate/",
      tags: ["finance"],
    },
    {
      id: "iit",
      title: "iit_title",
      description: "iit_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_iit_en.svg",
      images: {
        en: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_iit_en.svg",
        zh: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_iit_zh.svg",
      },
      link: "/tools/iit/",
      tags: ["finance"],
    },
    {
      id: "chartrace",
      title: "chartrace_title",
      description: "chartrace_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_chartrace_en.svg",
      images: {
        en: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_chartrace_en.svg",
        zh: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_chartrace_zh.svg",
      },
      link: "/tools/chartrace/",
      tags: ["chart", "data"],
    },
    {
      id: "subtitles",
      title: "subtitles_title",
      description: "subtitles_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_subtitles_en.svg",
      images: {
        en: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_subtitles_en.svg",
        zh: "https://slefboot-1251736664.file.myqcloud.com/20260418_ai_gallery_subtitles_zh.svg",
      },
      link: "/tools/subtitles/",
      tags: ["media"],
    },
  ],
};

export default Projects;
