const Projects = {
  games: [
    {
      id: "gomoku",
      title: "gomoku_title",
      description: "gomoku_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20240704_ai_gallery_gomoku.png/webp",
      link: "/games/gomoku",
    },
    {
      id: "chess",
      title: "chess_title",
      description: "chess_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20240706_ai_gallery_chess.png/webp",
      link: "/games/chess",
    },
    {
      id: "tetris",
      title: "tetris_title",
      description: "tetris_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20240714_ai_gallery_tetris.gif",
      link: "/games/tetris",
    },
    {
      id: "2048",
      title: "2048_title",
      description: "2048_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20240710_ai_gallery_game2048.gif",
      link: "/games/2048",
    },
    {
      id: "snake",
      title: "snake_title",
      description: "snake_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20240714_ai_gallery_snake.gif",
      link: "/games/snake",
    },
  ],
  algorithms: [
    {
      id: "linkedlist",
      title: "linkedlist_title",
      description: "linkedlist_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20240726_ai_gallery_linkedlist.webp",
      link: "/algorithms/linkedlist/",
    },
    {
      id: "heap",
      title: "heap_title",
      description: "heap_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20240706_ai_gallery_heapv2.gif",
      link: "/algorithms/heap/",
    },
    {
      id: "stack",
      title: "stack_title",
      description: "stack_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20240726_ai_gallery_stack.webp",
      link: "/algorithms/stack/",
    },
    {
      id: "hashtable",
      title: "hashtable_title",
      description: "hashtable_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20240726_ai_gallery_hashtable.webp",
      link: "/algorithms/hashtable/",
    },
    {
      id: "dpcoin",
      title: "dpcoin_title",
      description: "dpcoin_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20240730_ai_gallery_dpcoin.webp",
      link: "/algorithms/dpcoin/",
    },
    {
      id: "hashring",
      title: "hashring_title",
      description: "hashring_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20240801_ai_gallery_hashring.webp",
      link: "/algorithms/hashring/",
    },
    {
      id: "jumphash",
      title: "jumphash_title",
      description: "jumphash_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20240809_ai_gallery_jumphash.webp",
      link: "/algorithms/jumphash/",
    },
    {
      id: "hanoitower",
      title: "hanoitower_title",
      description: "hanoitower_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20240812_ai_gallery_hanoitower.webp",
      link: "/algorithms/hanoitower/",
    },
    {
      id: "dijkstra",
      title: "dijkstra_title",
      description: "dijkstra_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20240709_ai_gallery_dijkstra_v3.gif",
      link: "/algorithms/dijkstra/",
    },
    {
      id: "astar",
      title: "astar_title",
      description: "astar_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20240706_ai_gallery_astar_path.gif",
      link: "/algorithms/astar/",
    },
    {
      id: "bfs_path",
      title: "bfs_path_title",
      description: "bfs_path_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20240706_ai_gallery_bfs_path.gif",
      link: "/algorithms/bfs_path/",
    },
    {
      id: "trie",
      title: "trie_title",
      description: "trie_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20240726_ai_gallery_trie.webp",
      link: "/algorithms/trie/",
    },
    {
      id: "skiplist",
      title: "skiplist_title",
      description: "skiplist_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20240728_ai_gallery_skiplist.webp",
      link: "/algorithms/skiplist/",
    },
    {
      id: "bloomfilter",
      title: "bloomfilter_title",
      description: "bloomfilter_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20240805_ai_gallery_bloomfilter.webp",
      link: "/algorithms/bloomfilter/",
    },
    {
      id: "ratelimit",
      title: "ratelimit_title",
      description: "ratelimit_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20240716_ai_gallery_ratelimit.gif",
      link: "/algorithms/ratelimit/",
    },
    {
      id: "tokenbucket",
      title: "tokenbucket_title",
      description: "tokenbucket_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20240726_ai_gallery_tokenbucket.webp",
      link: "/algorithms/tokenbucket/",
    },
  ],
  tools: [
    {
      id: "bar_chart_race",
      title: "bar_chart_race_title",
      description: "bar_chart_race_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20240708_ai_gallery_bar_chart_race.gif",
      link: "/tools/bar_chart_race/",
    },
    {
      id: "subtitles",
      title: "subtitles_title",
      description: "subtitles_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20240728_ai_gallery_subtitles.webp",
      link: "/tools/subtitles/",
    },
  ],
};

export default Projects;
